name: Scrape Class Sections
on:
  schedule:
    - cron: "0,30 * * * *"
  workflow_dispatch:
  push:
jobs:
  scrape-sections:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Scrape Class Sections
        run: pnpm tsx scripts/dump_sections --mode=mongodb --season=spring --year=2025
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      